# Generated by Django 2.2 on 2019-04-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20190421_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rand',
        ),
    ]
