# Generated by Django 2.2 on 2019-04-22 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_remove_customuser_rand'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
