# Generated by Django 2.2 on 2019-04-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_date published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
